# Generated by Django 4.2.4 on 2023-10-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
